#!/usr/bin/env bash
# Regenerate docs/site/reference/crates.md from each crate's Cargo.toml description / //! header.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; cd "$ROOT"
{
echo "# Crate reference"; echo ""
echo "Every crate directory under \`rustyredcore_THG/crates/\`. One line each, taken from the crate's own \`Cargo.toml\` description or \`//!\` header. Generated by \`scripts/gen-crate-reference.sh\`; regenerate when crates change."; echo ""
echo "| Crate | What it is |"; echo "|-------|------------|"
for d in rustyredcore_THG/crates/*/; do
  name=$(basename "$d")
  desc=$(grep -m1 -E '^description' "$d/Cargo.toml" 2>/dev/null | sed -E 's/^description[[:space:]]*=[[:space:]]*"//; s/"[[:space:]]*$//')
  [ -z "$desc" ] && desc=$(sed -n '1,30p' "$d/src/lib.rs" 2>/dev/null | grep -E '^//!' | sed -E 's#^//! ?##' | grep -v '^$' | head -1)
  one=$(printf '%s' "$desc" | sed -E 's/\. .*/./' | sed 's/|/\\|/g'); [ -z "$one" ] && one="(no description; see crate source)"
  echo "| \`$name\` | $one |"
done
} > docs/site/reference/crates.md
